### ISSUE TITLE
Coordinating rebuilding Bioconductor data packages

### ISSUE THREAD

**Issue by jdblischak** [bioconda/bioconda-utils#235]
This Issue is to coordinate all the changes being made to `bioconductor-skeleton` in its handling of Bioconductor data packages (and subsequently rebuilding them).

cc @bgruening @mbargull @daler

To do:

- [x] Install in conda R library even if user has a user-specific R library (#231)
- [x] Create `pre-unlink.sh` to uninstall the data package (#234, #238)
- [x] Check md5 checksum of downloaded package on Linux (#233)
- [x]  Determine order for re-building packages (`bioconda-utils dag` accepts multiple globs, not a list of package names, so I'm not sure the easiest way to do this)
- [x] Fix tarball download issues (#230, #236, #237)

By my count, there are 63 Bioconductor data packages that would need to be updated:

```
$ cd bioconda-recipes
$ git log -1 --pretty=oneline
fe2c4f1377c0b55ef4550b53f5a0e247686cc751 update seqkit to v0.7.2 (#6985)
$ find recipes/bioconductor-* -name post-link.sh | wc -l
63
```

**Comment by jdblischak** [comment]
The order in which we rebuild these is not critical. The CI builds will pass since they already passed previously. However, we won't be able to rebuild them all at once, so to minimize the effect on downstream users, I used `conda build-all` to order the packages based on their dependencies (this only made a difference for a few of the packages, which is why it is mostly alphabetical order). I suggest that once we finalize the recent updates to the recipe skeleton, we submit PRs with 5-10 recipes each (please advise if that is too many to fit into the CI time limits) in the following order (note that the total is 66 since some packages have multiple versions):

```
TMP=/tmp/bioc
mkdir -p $TMP
for pkg in recipes/bioconductor-*
do
  if [[ -e $pkg/post-link.sh ]]; then
    cp -R $pkg $TMP
  fi 
done
conda build-all $TMP --dry-run --matrix-conditions "r-base ==3.4.1" | \
  grep bioconductor- | \
  cut -d'-' -f1-3 | \
  sed s/\\t/'- [ ] '/
```

- [ ] bioconductor-affydata-1.26.0
- [ ] bioconductor-all-1.20.0
- [ ] bioconductor-bladderbatch-1.14.0
- [ ] bioconductor-bsgenome.celegans.ucsc.ce10-1.4.0
- [ ] bioconductor-bsgenome.celegans.ucsc.ce6-1.4.0
- [ ] bioconductor-bsgenome.dmelanogaster.ucsc.dm3-1.4.0
- [ ] bioconductor-bsgenome.ecoli.ncbi.20080805-1.3.1000
- [ ] bioconductor-bsgenome.hsapiens.ucsc.hg19-1.4.0
- [ ] bioconductor-bsgenome.hsapiens.ucsc.hg38-1.4.1
- [ ] bioconductor-bsgenome.mmusculus.ucsc.mm10-1.4.0
- [ ] bioconductor-bsgenome.mmusculus.ucsc.mm9-1.4.0
- [ ] bioconductor-curatedovariandata-1.16.0
- [ ] bioconductor-do.db-2.9
- [ ] bioconductor-egseadata-1.6.0
- [ ] bioconductor-gagedata-2.16.0
- [ ] bioconductor-gcspikelite-1.16.0
- [ ] bioconductor-genelendatabase-1.14.0
- [ ] bioconductor-genomeinfodbdata-0.99.1
- [ ] bioconductor-go.db-3.5.0
- [ ] bioconductor-hom.hs.inp.db-3.1.2
- [ ] bioconductor-hsmmsinglecell-0.112.0
- [ ] bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19-0.6.0
- [ ] bioconductor-jaspar2014-1.14.0
- [ ] bioconductor-jaspar2016-1.6.0
- [ ] bioconductor-kegg.db-3.2.3
- [ ] bioconductor-keggdzpathwaysgeo-1.16.0
- [ ] bioconductor-org.bt.eg.db-3.5.0
- [ ] bioconductor-org.ce.eg.db-3.2.3
- [ ] bioconductor-org.cf.eg.db-3.5.0
- [ ] bioconductor-org.dm.eg.db-3.5.0
- [ ] bioconductor-org.dm.eg.db-3.3.0
- [ ] bioconductor-org.dr.eg.db-3.5.0
- [ ] bioconductor-org.gg.eg.db-3.5.0
- [ ] bioconductor-org.hs.eg.db-3.5.0
- [ ] bioconductor-org.mm.eg.db-3.5.0
- [ ] bioconductor-org.mm.eg.db-3.3.0
- [ ] bioconductor-org.rn.eg.db-3.5.0
- [ ] bioconductor-org.ss.eg.db-3.5.0
- [ ] bioconductor-pchicdata-1.6.0
- [ ] bioconductor-qdnaseq.mm10-1.8.0
- [ ] bioconductor-qdnaseq.mm10-1.4.0
- [ ] bioconductor-snplocs.hsapiens.dbsnp144.grch38-0.99.20
- [ ] bioconductor-txdb.celegans.ucsc.ce11.refgene-3.4.2
- [ ] bioconductor-txdb.celegans.ucsc.ce6.ensgene-3.2.2
- [ ] bioconductor-txdb.dmelanogaster.ucsc.dm3.ensgene-3.2.2
- [ ] bioconductor-txdb.dmelanogaster.ucsc.dm6.ensgene-3.4.1
- [ ] bioconductor-txdb.drerio.ucsc.danrer10.refgene-3.4.2
- [ ] bioconductor-txdb.hsapiens.ucsc.hg18.knowngene-3.2.2
- [ ] bioconductor-txdb.hsapiens.ucsc.hg19.knowngene-3.2.2
- [ ] bioconductor-txdb.hsapiens.ucsc.hg19.lincrnastranscripts-3.2.2
- [ ] bioconductor-txdb.hsapiens.ucsc.hg38.knowngene-3.4.0
- [ ] bioconductor-txdb.mmusculus.ucsc.mm10.ensgene-3.4.0
- [ ] bioconductor-txdb.mmusculus.ucsc.mm10.knowngene-3.4.0
- [ ] bioconductor-txdb.mmusculus.ucsc.mm9.knowngene-3.2.2
- [ ] bioconductor-txdb.rnorvegicus.ucsc.rn4.ensgene-3.2.2
- [ ] bioconductor-txdb.rnorvegicus.ucsc.rn5.refgene-3.4.2
- [ ] bioconductor-txdb.rnorvegicus.ucsc.rn6.refgene-3.4.1
- [ ] bioconductor-txdb.scerevisiae.ucsc.saccer2.sgdgene-3.2.2
- [ ] bioconductor-txdb.scerevisiae.ucsc.saccer3.sgdgene-3.2.2
- [ ] bioconductor-yeastexpdata-0.24.0
- [ ] bioconductor-fdb.infiniummethylation.hg19-2.2.0
- [ ] bioconductor-hgu133a.db-3.2.3
- [ ] bioconductor-hgu133plus2.db-3.2.3
- [ ] bioconductor-homo.sapiens-1.3.1
- [ ] bioconductor-illuminamousev2.db-1.26.0
- [ ] bioconductor-mgug4122a.db-3.2.3

**Comment by jdblischak** [comment]
I submitted the first 5 recipes in https://github.com/bioconda/bioconda-recipes/pull/7092.

I wrote a [script](https://github.com/jdblischak/jdb-conda/blob/master/scripts/rebuild-bioc-data.py) to help with this. If you'd like to help with this effort, please label the packages with the PR you submit to staged-recipes.

**Comment by mjsteinbaugh** [comment]
I'm happy to help with this

**Comment by jdblischak** [comment]
@mjsteinbaugh Awesome! To get started, how about you take the next 5 packages? You'll need conda-build version 2 and the most recent version of bioconda-utils. Please let me know if you have any questions. Thanks!

**Comment by mjsteinbaugh** [comment]
Sure I'll set that up this weekend and give it a go.

**Comment by bgruening** [comment]
@jdblischak we can make this very easy. Please create a PR against the `bulk` branch. I will merge it and then re-run travis until all packages are build.

How important is this? Can this wait until R 3.5, or is this more pressing?

**Comment by jdblischak** [comment]
> we can make this very easy. Please create a PR against the bulk branch. I will merge it and then re-run travis until all packages are build.

@bgruening That'd be great!

@mjsteinbaugh Have you had chance to look at this? I appreciate your help and don't want to duplicate effort. If you only want to commit to fixing 5-10 packages, you can send them to the "master" branch as originally planned. If you'd like to fix 10+ packages, please submit to the "bulk" branch. I'll finish however many are remaining after your PR.

> How important is this? Can this wait until R 3.5, or is this more pressing?

In my opinion this is pressing because these packages are barely functional. From most to least problematic:

1. They are not uninstalled after running `conda remove`
2. The  md5 checksum of the downloaded tarball is not properly verified on linux machines
3. If the end user has an R user library, the packages are installed there instead of in the conda library
4. The cargo port URL is wrong

**Comment by jdblischak** [comment]
I'd like to push this through faster. We need to fix these packages before updates to the packages are merged, e.g. https://github.com/bioconda/bioconda-recipes/pull/7102. I'm going to prepare a big PR to submit to "bulk"

**Comment by mjsteinbaugh** [comment]
@jdblischak Haven't finished that yet but have some time today to work on it

**Comment by jdblischak** [comment]
@mjsteinbaugh I apologize for the confusion. I switched the strategy on you based on @bgruening's suggestion to use the bulk branch. If you still have some time today to work on this, the most useful thing would be to review my PR https://github.com/bioconda/bioconda-recipes/pull/7116. We want to ensure that each package 1) has an updated `post-link.sh` that specifies the `--library`, 2) has a `pre-unlink.sh` file, and 3) has the build version increased by 1.

**Comment by jdblischak** [comment]
Closing now that most of these packages have been fixed and the few edge cases left to be resolved are being tracked elsewhere.
