### ISSUE TITLE
Autobump

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#354]
Closing #348 and #345 in favor of this one.

The update scanner is working in principle (#347), this lists remaining work items

**Please edit the issue body as needed - this thing is already too long.** (Think we should split into multiple issues?)

ping @bioconda/core - Could you review #347?

---

## Todo:

* [x] Find a good name :) - EDIT: calling it autobump

### Base update infrastructure (Recipe, Scanner)
* [x] Randomize recipe order  <details><summary>details</summary>
As requested in #348, the order in which recipes are scanned is now randomized. This is mainly to prevent the Bioconductor release cycle from clogging the pipeline. (Thinking about this, randomizing doesn't really fix this, might be more useful to balance the number of updates for each hosting sites, so that if 50 updates are allowed, each hoster get's an equal share).  </details>
* [x] Multi-output packages (`outputs:`)  <details><summary>details</summary>
Each recipe has a directory name and a top level package name, which are usually identical. With `outputs:` we can, however, have multiple packages built by one recipe. This needs handling when checking for conflicts with CF packages.  </details>
* [x] Send appropriate user agent <details><summary>details</summary> 
We should be identifying ourselves properly for each request we make. We are a bot after all. </details> 
* [x] Line selectors   (`# [linux]`) <details><summary>details</summary>
A lot of recipes have `# [linux]` style line selectors, which are currently ignored (see also #349). Very commonly, this is used in recipes not building from source to download the platform specific binaries. During parsing of the YAML, this leads to a duplicate key (`source: url` occurs twice), which needs handling. </details>

### User interaction (PR and git branches)
* [x] Ping maintainers  (`extra: maintainer`)
* [x] Fix PR title if upstream updates again while our update is active  <details><summary>details</summary>  
**Solution:** When loading a recipe from an active branch, the recipe from master is also loaded and considered the point of origin (`recipe.orig`).  </details>
* [x] Labels should not be removed when updating PR  <details><summary>details</summary>  
Setting labels via the API does not add, but replace the set of labels.
**Solution:** We don't set labels at all if the PR exists.
If we ever need to add labels, we will have to do load-change-set (accepting the parallel modify problem as rare and minor).  </details>
* [x] No PR spamming  <details><summary>details</summary>  
There should never be more than one PR opened per (recipe,version) pair.
**Solution**: 1) If an open PR exists for the update branch, its title and body are updated as needed. 2) If a closed PR exists for the update branch containing the current version in its title, we consider the update rejected (caveat: the branch persists for these, to persist the update that has already been tried). 3) Otherwise, a new PR is created.  </details>
* [x] Consistent local and remote update branches  <details><summary>details</summary>  
Changes made to the primary bioconda repo and the update branch at github need to be considered when updating.
**Solution**: 1) Local branches are always discarded when loading a Recipe using git. 2) Remote branches are checked against `master`. If anything in the recipe directory has been modified since the branch forked from master, the branch is discarded.  </details>
* [x] Change branches to `bioconda/bioconda-recipes:bump/{recipe}{/subdir}` <details><summary>details</summary>  
After a while of working with this, I believe the update branches should live in the main bioconda-recipes repo. This is the only way everyone can trivially check out one of those branches and push updates, so it justifies the bit of extra mess.
I'm not set on a naming scheme, but perhaps `bump/{recipe_dir}{/recipe_subdir}` 
Update: Using `bump/{recipe_dir}{.d/recipe_subdir}` as tags. The `.d` is necessary because git actually uses directories here, so we can't have both `x` and `x/1` as branches at the same time.</details> 
* ~~Ping contributors~~ **Rejected:** data not easily available<details><summary>details</summary>  
Since we don't have maintainers for many recipes, it may be helpful to ping contributors to the recipe. We can get these from the git log. To prevent spam, this should produce active pings if no maintainers field exists (empty means do not ping contributors). It should also determine if contributors are Bioconda members and ping only those (considering membership opt in for pings seems reasonable). 
**Rejected:**To do this, we'd have to get the github account name from the email in the git commit log. This is difficult to do for users like Bjoern who commit with an email that isn't in their public profile.</details> 
* [x] Ping upstream author <details><summary>details</summary>  
For packages hosted on github, we can also ping the upstream author to inform him/her of the update. Applying the same filters as for contributors (only members, not if maintainers set), should limit spam. </details> 
* ~~Show recent versions in PR body~~ **Rejected:** visible from version jump <details><summary>details</summary>  
It might be useful to provide a list of recent releases in the PR body, to make it easier to check whether this is an update we want, or if there were so many updates that the recipe needs more in depth testing. </details> 

### Upstream parsing (hosters)
* [x] Parse Github tags (github.com/.../archive)
* [x] Parse Github custom releases (github.com/.../releases)
* [x] Parse Bioconductor (bioconductor.org)
* [x] Parse Cargo-Port (depot.galaxy.org)
* [x] Parse Bioarchive (bioarchive.galaxyproject.org)
* [x] Parse CRAN (cloud.r-project.org, cran.r-project.org)
* [x] Parse CPAN (cpan.metapan.org, search.cpan.org)
* [x] Parse PyPi (pypi.io, pypi.python.org, files.pythonhosted.org)
* [x] Parse Sourceforge (downloads.sourceforge.net, sourceforge.net)
* [x] Parse Bitbucket
* [x] Parse Gitlab (gitlab.com, self hosted?)  <details><summary>details</summary>  
Some of the self hosted tools may actually use gitlab installations. </details> 
* [x] Parse FTP  <details><summary>details</summary>  
Extra infrastructure is needed to get files and listings from FTP sites. `aiohttp` is, as the name suggests, limited to HTTP, but no equivalent (good) project for ftp appears to exist. </details> 
* ~~Parse custom~~ moved to  #437 <details><summary>details</summary>   
For scraping updates from individual hosting sites (e.g. universities, labs), parameters should be configurable from the recipe itself. This should also allow overriding parameters for existing hosters, e.g. to allow customizing for rare release schemes etc, while allowing centralized updates to the hoster (I think this may be needed for source forge).  </details> 

### Extra features
* [x] Check upstream dependency changes  <details><summary>details</summary>  
CRAN and CPAN provide dependency information for their packages. PyPi does not, but the packages do and could be parsed. Bioarchive contains dependency information in some cases. Some upstream packages may have a `*/meta.yaml` file or an `environment.yaml` file that provides structured dependency information. These could be used to add information to the PR body regarding dependency changes, or even to update the dependencies automatically. </details> 
   * [x] CRAN
   * [x] CPAN
   * [x] Python
   * environment.yaml?
*  ~~Exclude updates with dependencies that cannot be satisfied~~ implemented but slow and disabled  <details><summary>details</summary>  
Having the updated versions dependencies, we can check them against the pins from the active build variant config and against available packages. Not an issue for us so far, but could be useful. It might be sensible though to have some form of output (e.g. an issue stating that package X is needed to update package Y to it's most recent version).  </details> 
* ~~Repair recipes with missing checksum~~ fixed manually  <details><summary>details</summary>  
Currently, `md5` checksums are replaced with `sha256` checksums, but if the checksum is missing all together (some pre-linting recipes), we are not setting it. We should just add it same as we do for the build number if it is missing. </details> 
* ~~Remove run deps that are made redundant by `run_exports`~~ Linter ticket #379
* ~~Fix attribution~~ **Rejected:** needs bot <details><summary>details</summary>  
Currently, attribution goes solely to the initiator of the PR. (Embarrasingly, that's currently me for all the bumps...). Github does parse the `Co-authored-by:` trailer, so we could add that to the merge body to attribute contributions correctly. Since GH doesn't add this on its own, we would need to have a bot creating and pushing the merge commits, though. 
See https://git.wiki.kernel.org/index.php/CommitMessageConventions for standard trailers. </details>

**Comment by epruesse** [comment]
Technically it could run in a cron, sure. I'd like to keep it semi-manual for a while longer though because I'm using the updates that come in as test cases. Maybe I should write unit tests instead. Just shying from that because of the effort involved.

I do think that tracking upstream dependency changes as far as possible is needed, though. Right now, that's the most time consuming part. While it's tempting to just merge if an update builds ok, many recipes have only minimal tests that won't catch subtle breakage due to changes in dependency requirements. New dependencies we should catch, sure, but technically we'd have to check for ">0.5.1" vs ">0.5.2" for each requirement in the Python/Perl/R packages as those may only cause problems in very specific situations.

**Comment by epruesse** [comment]
I'm creating the bump branches within the Bioconda repository now.

Sorry about the churn - I had to close the ~80 old PRs and create new ones as I can't change the source branch for an existing PR.
